name: Terraform OIDC

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login with OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Check Azure Login
        shell: powershell
        run: az account show

      - name: Terraform Version
        shell: powershell
        run: terraform --version

      - name: Terraform Init
        shell: powershell
        run: terraform init

      - name: Terraform Validate
        shell: powershell
        run: terraform validate

      - name: Terraform Plan
        shell: powershell
        run: terraform plan

      - name: Terraform Apply
        shell: powershell
        run: terraform apply -auto-approve
