name: Terraform Pipeline

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:

  terraform-plan:
    uses: ./.github/workflows/terraform-template.yml

    with:
      working_directory: envir/dev
      environment: dev

    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
