name: Terraform Reusable Workflow

on:
  workflow_call:
    inputs:
      working_directory:
        required: true
        type: string

      environment:
        required: true
        type: string

    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

jobs:

  terraform:
    name: Terraform ${{ inputs.environment }}

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}

    steps:

      # Checkout
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Azure OIDC Login
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Init
      - name: Terraform Init
        run: terraform init

      # Format
      - name: Terraform Format
        run: terraform fmt -check

      # Validate
      - name: Terraform Validate
        run: terraform validate

      # Plan
      - name: Terraform Plan
        run: terraform plan
